const $ = s => document.querySelector(s);
const state = { user: null, items: [], sales: [], expenses: [{name:'Storage unit',amount:64,date:'2026-09-05'},{name:'Packaging supplies',amount:22.40,date:'2026-09-14'}] };
const seed = [{name:'Nike Dunk Low “Panda”',category:'Sneakers',cost:78,price:130,source:'Vinted',date:'2026-09-12',status:'In stock'},{name:'Carhartt Detroit Jacket',category:'Clothing',cost:55,price:145,source:'Depop',date:'2026-09-15',status:'In stock'},{name:'Sony WH-1000XM5',category:'Electronics',cost:160,price:215,source:'eBay',date:'2026-09-17',status:'In stock'},{name:'New Balance 2002R',category:'Sneakers',cost:70,price:120,source:'Outlet',date:'2026-09-01',status:'Sold'}];
function money(n){return new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n)}
function save(){localStorage.setItem('resellrData',JSON.stringify({items:state.items,sales:state.sales,expenses:state.expenses}));}
function load(){let data=JSON.parse(localStorage.getItem('resellrData')||'null'); if(data)Object.assign(state,data); else {state.items=seed;state.sales=[seed[3]];save()} state.user=JSON.parse(localStorage.getItem('resellrUser')||'null');}
function totalProfit(){return state.items.filter(x=>x.status==='Sold').reduce((n,x)=>n+x.price-x.cost,0)-state.expenses.reduce((n,x)=>n+x.amount,0)}
function inventoryValue(){return state.items.filter(x=>x.status!=='Sold').reduce((n,x)=>n+x.cost,0)}
function nav(page){document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('.app').classList.remove('menu-open'); let t={dashboard:['BUSINESS OVERVIEW',`Good morning, ${state.user?.name?.split(' ')[0]||'there'}`],inventory:['YOUR STOCK','Inventory'],sales:['MONEY IN','Sales'],expenses:['MONEY OUT','Expenses'],analytics:['YOUR PERFORMANCE','Analytics'],settings:['PREFERENCES','Settings']}[page];$('#pageKicker').textContent=t[0];$('#pageTitle').textContent=t[1]; $('#addButton').style.display=page==='settings'?'none':'flex'; render(page)}
function dashboard(){let available=state.items.filter(x=>x.status!=='Sold').length;return `<div class="dashboard-grid"><div class="card"><span class="trend">+12.4%</span><p class="metric-label">Total profit</p><p class="metric-number">${money(totalProfit())}</p></div><div class="card"><span class="trend">${state.sales.length} sold</span><p class="metric-label">Sales revenue</p><p class="metric-number">${money(state.sales.reduce((n,x)=>n+x.price,0))}</p></div><div class="card"><p class="metric-label">Inventory value</p><p class="metric-number">${money(inventoryValue())}</p></div><div class="card"><span class="trend red">${state.expenses.length} costs</span><p class="metric-label">Monthly expenses</p><p class="metric-number">${money(state.expenses.reduce((n,x)=>n+x.amount,0))}</p></div></div><div class="content-grid"><section class="card chart-card"><h3>Profit performance</h3><p class="chart-key">Weekly net profit · September</p><div class="chart"><div class="bar-group" data-day="Mon"><i class="bar" style="height:33%"></i><i class="bar dark" style="height:56%"></i></div><div class="bar-group" data-day="Tue"><i class="bar" style="height:42%"></i><i class="bar dark" style="height:37%"></i></div><div class="bar-group" data-day="Wed"><i class="bar" style="height:58%"></i><i class="bar dark" style="height:76%"></i></div><div class="bar-group" data-day="Thu"><i class="bar" style="height:48%"></i><i class="bar dark" style="height:67%"></i></div><div class="bar-group" data-day="Fri"><i class="bar" style="height:70%"></i><i class="bar dark" style="height:92%"></i></div><div class="bar-group" data-day="Sat"><i class="bar" style="height:51%"></i><i class="bar dark" style="height:70%"></i></div></div></section><section class="card"><h3>Recent activity</h3><div class="activity">${state.items.slice(-4).reverse().map(x=>`<div class="activity-row"><span class="dot">${x.status==='Sold'?'↗':'□'}</span><p>${x.status==='Sold'?'Sold':'Added'} <strong>${x.name}</strong><small>${x.source||'Manual entry'} · ${x.date||'Today'}</small></p><span class="profit">${x.status==='Sold'?'+':''}${money(x.status==='Sold'?x.price-x.cost:x.price)}</span></div>`).join('')}</div></section></div><div class="section-head"><div><h2>Inventory snapshot</h2><p>${available} items ready to sell</p></div><button class="nav-link" data-page="inventory">View all →</button></div>${table(state.items.slice(0,4))}`}
function table(items){if(!items.length)return `<section class="card empty"><strong>Nothing here yet</strong>Add your first item to start tracking it.</section>`;return `<section class="card table-card"><table class="inventory-table"><thead><tr><th>ITEM</th><th>CATEGORY</th><th>PURCHASE</th><th>EXPECTED SALE</th><th>PROFIT</th><th>STATUS</th></tr></thead><tbody>${items.map(x=>`<tr><td><span class="product"><span class="product-icon">${x.category==='Sneakers'?'◒':x.category==='Electronics'?'◉':'◇'}</span>${x.name}</span></td><td>${x.category}</td><td>${money(x.cost)}</td><td>${money(x.price)}</td><td style="color:var(--green);font-weight:700">${money(x.price-x.cost)}</td><td><span class="status ${x.status==='Sold'?'sold':''}">${x.status}</span></td></tr>`).join('')}</tbody></table></section>`}
function inventory(){return `<div class="section-head"><div><h2>All inventory</h2><p>Everything you have sourced, in one place.</p></div><div class="summary-pills"><span class="pill">${state.items.filter(x=>x.status!=='Sold').length} active</span><span class="pill">${money(inventoryValue())} invested</span></div></div>${table(state.items)}`}
function sales(){let sold=state.items.filter(x=>x.status==='Sold');return `<div class="section-head"><div><h2>Sales</h2><p>Completed sales and your realised returns.</p></div><span class="pill">${money(sold.reduce((n,x)=>n+x.price,0))} revenue</span></div>${table(sold)}`}
function expenses(){let total=state.expenses.reduce((n,x)=>n+x.amount,0);return `<div class="dashboard-grid"><div class="card"><p class="metric-label">Total expenses</p><p class="metric-number">${money(total)}</p></div><div class="card"><p class="metric-label">Transactions</p><p class="metric-number">${state.expenses.length}</p></div></div><div class="section-head"><div><h2>Operating costs</h2><p>Costs not attached to a specific item.</p></div></div><section class="card table-card"><table class="inventory-table"><thead><tr><th>DESCRIPTION</th><th>DATE</th><th>AMOUNT</th></tr></thead><tbody>${state.expenses.map(x=>`<tr><td class="product"><span class="product-icon">◫</span>${x.name}</td><td>${x.date}</td><td style="color:var(--red);font-weight:700">−${money(x.amount)}</td></tr>`).join('')}</tbody></table></section>`}
function analytics(){let sourced=state.items.reduce((n,x)=>n+x.cost,0), potential=state.items.reduce((n,x)=>n+x.price-x.cost,0);return `<div class="dashboard-grid"><div class="card"><p class="metric-label">Potential profit</p><p class="metric-number">${money(potential)}</p></div><div class="card"><p class="metric-label">Average margin</p><p class="metric-number">${state.items.length?Math.round(potential/sourced*100):0}%</p></div><div class="card"><p class="metric-label">Items tracked</p><p class="metric-number">${state.items.length}</p></div><div class="card"><p class="metric-label">Best category</p><p class="metric-number">Sneakers</p></div></div><section class="card chart-card" style="margin-top:15px"><h3>Expected return by item</h3><p class="chart-key">Your active inventory’s projected margin</p><div class="chart">${state.items.filter(x=>x.status!=='Sold').map((x,i)=>`<div class="bar-group" data-day="${i+1}"><i class="bar dark" style="height:${Math.min(95,Math.round((x.price-x.cost)/x.price*150))}%"></i></div>`).join('')}</div></section>`}
function settings(){return `<section class="card settings-card"><div class="setting-row"><div><p>Appearance</p><small>Switch between light and dark workspace colours.</small></div><button id="settingsTheme" class="switch"><span></span></button></div><div class="setting-row"><div><p>Storage mode</p><small>Local browser data · Supabase not configured</small></div><span class="pill">Demo</span></div><div class="setting-row"><div><p>Your account</p><small>${state.user?.email||''}</small></div></div></section>`}
function render(page){$('#pageContent').innerHTML=({dashboard,inventory,sales,expenses,analytics,settings}[page]()); document.querySelectorAll('.nav-link').forEach(x=>x.onclick=()=>nav(x.dataset.page)); $('#settingsTheme')?.addEventListener('click',toggleTheme)}
function toggleTheme(){document.body.classList.toggle('dark');localStorage.setItem('resellrTheme',document.body.classList.contains('dark')?'dark':'light')}
function enter(user){state.user=user;localStorage.setItem('resellrUser',JSON.stringify(user));$('#authView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#avatar').textContent=(user.name||'A')[0].toUpperCase();nav('dashboard')}
$('#loginForm').addEventListener('submit',e=>{e.preventDefault();let email=$('#loginEmail').value,password=$('#loginPassword').value,users=JSON.parse(localStorage.getItem('resellrUsers')||'[]');let user=users.find(x=>x.email===email&&x.password===password)||(email==='demo@resellr.app'&&password==='demo1234'?{name:'Alex',email}:null);if(user)enter(user);else $('#authMessage').textContent='That email and password do not match.'});
$('#registerForm').addEventListener('submit',e=>{e.preventDefault();let user={name:$('#registerName').value,email:$('#registerEmail').value,password:$('#registerPassword').value};let users=JSON.parse(localStorage.getItem('resellrUsers')||'[]');if(users.some(x=>x.email===user.email)){alert('An account with that email already exists.');return}users.push(user);localStorage.setItem('resellrUsers',JSON.stringify(users));enter(user)});
document.querySelectorAll('[data-auth]').forEach(x=>x.onclick=()=>{$('#loginForm').classList.toggle('hidden');$('#registerForm').classList.toggle('hidden')});document.querySelectorAll('[data-page]').forEach(x=>x.addEventListener('click',()=>nav(x.dataset.page)));$('#themeToggle').onclick=toggleTheme;$('#menuButton').onclick=()=>$('.app').classList.toggle('menu-open');$('#signOut').onclick=()=>{localStorage.removeItem('resellrUser');location.reload()};$('#addButton').onclick=()=>{$('#itemDialog').showModal();$('#itemForm [name=date]').value=new Date().toISOString().slice(0,10)};$('#itemForm').addEventListener('submit',()=>{let f=new FormData($('#itemForm')),x=Object.fromEntries(f);x.cost=+x.cost;x.price=+x.price;x.status='In stock';state.items.unshift(x);save();setTimeout(()=>nav('inventory'))});load();if(localStorage.getItem('resellrTheme')==='dark')document.body.classList.add('dark');if(state.user)enter(state.user);
